[package]
name = "acmon"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
etcd-client = "0.7"
serde = "1"
serde_yaml = "0.8"
async-trait = "0.1"
# http2 is only enabled because hyper-tls forces this feature https://github.com/rustls/hyper-rustls/issues/143
hyper = { version = "0.14", default-features = false, features = ["server", "http1", "http2", "stream", "runtime", "client"] }
tower = { version = "0.4", default-features = false, features = ["retry"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.2"
futures-util = "0.3"
hyper-rustls = {version = "0.22", default-features = false, features = ["webpki-tokio"]}
serde_json = "1"
warp = { version = "0.3", default-features = false }
thiserror = "1"
pin-project-lite = "0.2"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres"]}
either = "1.5"

[dev-dependencies]
wiremock = "0.5"
cached = { version = "0.24", default-features = false, features = ["async"]}
parking_lot = "0.11"
tokio-util = "0.6"
serde_test = "1"
etcd-client = { version = "0.7", features = ["pub-response-field"] }
tower-test = "0.4"
mockall = "0.10"
testcontainers = "0.12"

[features]
container = []
